config/routes.rb
Rails.application.routes.draw do
	root 'places#index'
  resources :categories
  resources :places do 
    resources :ratings
  end
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    user.admin?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :places
	validates :name, presence: true,
  				   uniqueness: true,
  				   length: {minimum:1}
end

app/models/place.rb
class Place < ApplicationRecord
	has_many :ratings
	belongs_to :user
	belongs_to :category
	validates :name, presence: true,
            uniqueness: true,
            length: {minimum: 3}
	validates :description, presence: true,
            length: {maximum: 5400}
end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :user
	belongs_to :place
end

app/models/user.rb
class User < ApplicationRecord
	has_many :places
	has_many :ratings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	validates :name, presence: true, uniqueness: true, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end

  def ensure_admin!
    unless user_signed_in?
      redirect_to root_path

      return false
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
	before_action :set_category, only: [:show, :edit, :update, :destroy]
	before_action :ensure_admin!, only: [:new, :create]
	def index
    @categories = Category.all
  end

  def show
  	@places = Place.where(:category => params[:category])
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to root_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   
    def set_category
      @category = Category.find(params[:id])
    end
  private

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/places_controller.rb
class PlacesController < InheritedResources::Base
before_action :set_place, only: [:show, :edit, :update, :destroy]
before_action :ensure_admin!, only: [:new, :create]

	def index
		@categories = Category.all
    if params[:category]
    	@places = Place.where(:category => params[:category], active: true)
  	else
    	@places = Place.where(active: true)
    end
  end

  def show
  	@overall = Place.average_score
    @food_average = @place.reviews.average(:food)
    @food_average = @food_average.round(1) if @food_average
    @service_average = @place.reviews.average(:service)
    @service_average = @service_average.round(1) if @service_average
    @interior_average = @place.reviews.average(:interior)
    @interior_average = @interior_average.round(1) if @interior_average
    
    all_average = [@food_average, @service_average, @interior_average]
    if all_average == [nil, nil, nil]
      @overall_average = 0
    else
      @overall_average = (all_average.sum / all_average.size.to_f).round(1) if all_average
    end
  end

  def new
    @place = Place.new
  end

  def edit
  end

  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to root_path, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
  	def set_place
      @place = Place.find(params[:id])
    end

    def place_params
      params.require(:place).permit(:name, :description, :active, :user_id, :category_id)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < InheritedResources::Base

  def create
    place = Place.find(params[:place_id])
    rating = place.ratings.new rating_params
    rating.user = current_user
    rating.save
    redirect_to place_path(place)
  end

  private
  
    def rating_params
      params.require(:rating).permit(:text, :food_score, :service_score, :interior_score)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RateApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/application/navbar' %>
  <p id="notice"><%= notice %></p>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="#">About</a></li>
        <li><a href="#">Contacts</a></li>
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">
            Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'navbar-link' %>
          </p>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                <% if current_user.admin? %>
                  <li><%= link_to 'Admin', admin_root_path %></li>
                <% end %>
                <li class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %> <br>
    <%= form.text_field :name, id: :place_name %>
  </div>

  <div class="field">
    <%= form.label :description %> <br>
    <%= form.text_area :description, id: :place_description %>
  </div>

  <div class="field">
    <%= form.label :category_id %> <br>
    <%= form.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <br>
  <div class="field">
  <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>
<h4>Categories</h4>
<% @categories.each do |category| %>
<td><%= link_to category.name, places_path(:category => category.id) %></td>
<% end %>

<h1>Places</h1>
<div class="container-fluid">
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.description %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Place', new_place_path %>
<% end %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<br> <%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @place.description %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/ratings/_form.html.erb
<%= form_for [@place, Rating.new] do |f| %>
  
  <div class="field">
    <%= f.label "Review" %> <br>
    <%= f.text_area :text, id: :rating_text %>
  </div>

  <div class="field">
    <%= f.label :food_score %> <br>
    <%= f.select :food_score, [1, 2, 3, 4, 5] %>
  </div>

  <div class="field">
    <%= f.label :service_score %> <br>
    <%= f.select :service_score, [1, 2, 3, 4, 5] %>
  </div>

  <div class="field">
    <%= f.label :interior_score %> <br>
    <%= f.select :interior_score, [1, 2, 3, 4, 5] %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<br>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Back', ratings_path %>